(* ::Package:: *)

(* ::Input:: *)
(*ApproximateFrequency[data_,columnMissing_,columnReference_,missingEntry_]:=Module[{j,adjacentSpots,referenceSpacing,validEntries,fit},*)
(*validEntries=data[Select[#[[columnMissing]]>7000000&]];*)
(*referenceSpacing=data[[2]][[columnReference]]-data[[1]][[columnReference]];*)
(*j=1;*)
(*While[And[Length[adjacentSpots]<3,j*referenceSpacing<1024],*)
(*adjacentSpots=validEntries[Select[Abs[#[[columnReference]]-missingEntry]<=referenceSpacing*j&]];*)
(*j++;*)
(*];*)
(*fit=LinearModelFit[Normal[adjacentSpots],x,x];*)
(*fit[missingEntry]*)
(*];*)
(**)
(*FillInMissedFrequencies[data_,columnMissing_,columnReference_]:=Module[{referenceSpacing,missingEntries,validEntries,adjacentSpots,estimatedFrequency,linearModel,dataCopy,position,approxValue,data2,k},*)
(*data2=data;*)
(*dataCopy=Dataset[Take[data,{1,-1},{1,2}]];*)
(*missingEntries=dataCopy[Select[#[[columnMissing]]<7000000&]];*)
(*missingEntries=Transpose[Normal[missingEntries]][[columnReference]];*)
(*For[k=1,k<=Length[missingEntries],k++,*)
(*approxValue=ApproximateFrequency[dataCopy,columnMissing,columnReference,missingEntries[[k]]];*)
(*position=Position[dataCopy,missingEntries[[k]]][[1,1]];*)
(*data2[[position,columnMissing]]=approxValue;*)
(*];*)
(*data2*)
(*];*)
